name: jaspr_l10n
description: Basic localization generator for Jaspr
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.8

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
executables:
  jaspr_l10n:
